name: Continuous Integration

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip, wheel, pytest, jupyter
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install pytest
        pip install pytest-cov
        pip install jupyter
        pip install pyqsp

    - name: Install pycodestyle
      run: |
        python -m pip install pycodestyle

    - name: pycodestyle tests
      run: |
        cd other_tests
        pytest --doctest-modules --junitxml=junit/pycodestyle-test-results.xml test_conformance.py
      if: always()

    - name: Install backends except qsharp/qdk
      run: |
        pip install qiskit
        pip install qulacs
        pip install amazon-braket-sdk
        pip install cirq
        pip install projectq
        pip install pennylane
      if: always()

    - name: Install Microsoft qsharp/qdk
      run: |
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        sudo apt-get update; sudo apt-get install -y apt-transport-https && sudo apt-get update
        sudo apt-get install -y dotnet-sdk-5.0
        dotnet tool install -g Microsoft.Quantum.IQSharp
        $(which dotnet-iqsharp) install --user
        pip install qsharp
      if: always()

    - name: tangelo install
      env:
        NO_PYSCF: 1
      run: |
        python -m pip install .
      if: always()

    - name: tangelo no_pyscf tests
      run: |
        cd other_tests
        pytest --doctest-modules --junitxml=junit/nopyscf-test-results.xml test_nopyscf.py
      if: always()

    - name: Install pyscf
      env:
        NO_PYSCF: 0
      run: |
        python -m pip install pyscf
        python -m pip install git+https://github.com/pyscf/semiempirical
      if: always()

    - name: tangelo tests
      run: |
        cd tangelo
        pytest --doctest-modules --junitxml=junit/tangelo-test-results.xml --cov=. --cov-report=xml --cov-report=html
      if: always()

    - name: Upload nopyscf test results
      uses: actions/upload-artifact@v3
      with:
        name: tangelo-no-pyscf-test-results
        path: other_tests/junit/nopyscf-test-results.xml

    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: tangelo-test-results
        path: tangelo/junit/tangelo-test-results.xml

    - name: Upload pytest html results
      uses: actions/upload-artifact@v3
      with:
        name: tangelo-tests-coverage
        path: tangelo/htmlcov
      if: always()

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      if: always()
