name: Continuous Integration

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip, wheel, pytest, jupyter
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install pytest
        pip install pytest-cov
        pip install jupyter

    - name: Install pycodestyle
      run: |
        python -m pip install pycodestyle

    - name: pycodestyle tests
      run: |
        cd dev_tools
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html test_conformance.py
      if: always()

    - name: Install backends except qsharp/qdk
      run: |
        pip install qiskit
        pip install qulacs
        pip install amazon-braket-sdk
        pip install cirq
        pip install projectq
      if: always()

    - name: Install Microsoft qsharp/qdk
      run: |
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        sudo apt-get update; sudo apt-get install -y apt-transport-https && sudo apt-get update
        sudo apt-get install -y dotnet-sdk-5.0
        dotnet tool install -g Microsoft.Quantum.IQSharp
        $(which dotnet-iqsharp) install --user
        pip install qsharp
      if: always()

    - name: tangelo install
      run: |
        python -m pip install .
      if: always()

    - name: tangelo tests
      run: |
        cd tangelo
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      if: always()

    - name: tangelo notebooks as tests
      run: |
        cd examples
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html test_notebooks.py
      if: always()
