name: psi4 test

on: [pull_request]

env:
  NO_PYSCF: 1

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
    - run: conda info
    - run: conda list
    - run: conda config --show

    - name: Install psi4
      shell: bash -el {0}
      run: |
        conda create -n p4env psi4 -c psi4
        conda init
        conda activate p4env
      if: always()

    - name: Install pip, wheel, pytest, jupyter
      run: |
        conda activate p4env
        python -m pip install --upgrade pip
        pip install wheel
        pip install pytest
        pip install pytest-cov
    
    - name: Install qulacs
      run: |
        conda activate p4env
        pip install qulacs
      if: always()

    - name: tangelo install
      run: |
        conda activate p4env
        python -m pip install .
      if: always()

    - name: tangelo psi4 tests
      run: |
        cd other_tests
        conda activate p4env
        pytest --doctest-modules --junitxml=junit/psi4-test-results.xml test_psi4.py
      if: always()

    - name: Upload psi4 test results
      uses: actions/upload-artifact@v3
      with:
        name: tangelo-psi4-test-results
        path: other_tests/junit/psi4-test-results.xml

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      if: always()
